# Testing WordPress notification client

version: "3"
services:

  wordpress: 
    container_name: dwppt-wordpress # [app]-[component]-[service]
    # image: base
    links:
      - mysql
    ports:
      - "8080:80"
    volumes:
      - "./plugins:/var/www/html/wp-content/plugins" # The plugin to test
    environment:
      - WORDPRESS_DB_HOST=mysql
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_NAME=wordpress
      - BBNA_NOTIFICATIONCLIENT_ENDPOINT=http://mockendpoint
    healthcheck:
      test: 'wp core is-installed --allow-root'
    restart: unless-stopped

  mysql: 
    container_name: dwppt-mysql # [app]-[component]-[service]
    # image: base
    ports:
      - "33062:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
    restart: unless-stopped
